name: Build

on:
  push:
    branches:
    - 'main'
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Set up SNAPSHOT environment
      if: github.ref == 'refs/heads/main'
      run: |
        echo "GORELEASE_ARGS=build --clean --snapshot" >> $GITHUB_ENV

    - name: Set up RELEASE environment
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        echo "GORELEASE_ARGS=release --clean" >> $GITHUB_ENV

    - name: Tidy modules
      run: go mod tidy

    - name: Run tests
      run: go test -v ./...

    # - name: Build snapshot binaries
    #   uses: goreleaser/goreleaser-action@v2
    #   if: success() && github.ref == 'refs/heads/main'
    #   with:
    #     version: latest
    #     args: build --clean --snapshot

    - name: Run GoRelease
      uses: goreleaser/goreleaser-action@v2
      if: success()
      with:
        version: latest
        args: ${{env.GORELEASE_ARGS}}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_RELEASE_TOKEN }}

    # - name: Install Task
    #   uses: arduino/setup-task@v1
    #   with:
    #     version: 3.x

    # - name: Build
    #   run: task build
    #   if: startsWith(github.ref, 'refs/heads/')
