name: Build

on:
  push:
    branches:
    - 'main'
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - run: go mod tidy
    - run: go test -v ./...

    - uses: goreleaser/goreleaser-action@v2
      if: success() && github.ref == 'refs/heads/main'
      with:
        version: latest
        args: build --clean --snapshot

    # - name: Install Task
    #   uses: arduino/setup-task@v1
    #   with:
    #     version: 3.x

    # - name: Build
    #   run: task build
    #   if: startsWith(github.ref, 'refs/heads/')
